apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: db
  ports:
    - port: 27017
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 27017
