name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for client
        working-directory: ./client
        run: npm install

      - name: Install dependencies for server
        working-directory: ./server
        run: npm install

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run server tests
        working-directory: ./server
        run: npm test

      - name: Run client tests
        working-directory: ./client
        run: npm test

      - name: Build client
        working-directory: ./client
        run: npm run build

  build_and_push_docker_images:
    runs-on: ubuntu-latest
    needs: run_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for server
        run: |
          docker build -t vedaangss/server:latest ./server

      - name: Build Docker image for client
        run: |
          docker build -t vedaangss/client:latest ./client

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image for server
        run: |
          docker push vedaangss/server:latest

      - name: Push Docker image for client
        run: |
          docker push vedaangss/client:latest

      - name: Archive client build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: client-build
          path: ./client/build
