name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: node:16-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: npm install

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16-alpine

      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  build_and_push_docker_images:
    runs-on: ubuntu-latest
    needs: run_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for backend
        run: |
          docker build -t vedaangss/backend:latest ./backend

      - name: Build Docker image for frontend
        run: |
          docker build -t vedaangss/frontend:latest ./frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image for backend
        run: |
          docker push vedaangss/backend:latest

      - name: Push Docker image for frontend
        run: |
          docker push vedaangss/frontend:latest

      - name: Archive frontend build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./frontend/build
